name: Release Insiders

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Calculate environment variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'Version `radix-icons` based on commit: 0.0.0-insiders.${{ env.SHA_SHORT }}'
        run: pnpm version 0.0.0-insiders.${{ env.SHA_SHORT }} --force --no-git-tag-version

      - name: 'Version `@radix-icons/react` based on commit: 0.0.0-insiders.${{ env.SHA_SHORT }}'
        run: pnpm version 0.0.0-insiders.${{ env.SHA_SHORT }} --force --no-git-tag-version --prefix react

      - name: 'Version `@radix-icons/vue` based on commit: 0.0.0-insiders.${{ env.SHA_SHORT }}'
        run: pnpm version 0.0.0-insiders.${{ env.SHA_SHORT }} --force --no-git-tag-version --prefix vue

      - name: Publish `radix-icons`
        run: pnpm publish --tag insiders --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish `@radix-icons/react`
        run: pnpm publish ./react --tag insiders --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish `@radix-icons/vue`
        run: pnpm publish ./vue --tag insiders --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
